kind: Service
apiVersion: v1
metadata:
  name: hotel-service
spec:
  selector:
    run: hotel-service
  ports:
    - name: port1
      protocol: TCP
      port: 6100
      targetPort: 6100
  type: NodePort