kind: Service
apiVersion: v1
metadata:
  name: holiday-service
spec:
  selector:
    run: holiday-service
  ports:
    - name: port1
      protocol: TCP
      port: 6200
      targetPort: 6200
  type: NodePort