kind: Service
apiVersion: v1
metadata:
  name: aishello-service
spec:
  selector:
    run: aishello-service
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort